# Generated by Django 5.1.5 on 2025-03-06 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_registration_delete_participant'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='player_number',
            field=models.PositiveIntegerField(default=1, unique=True),
        ),
    ]
