# Generated by Django 5.1.5 on 2025-03-06 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_registration_player_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='player_number',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
    ]
